"use strict";

/* ==========================================================================
   FOSFORO · i18n.js
   Lingua dell'interfaccia scelta dall'utente, non dal browser.

   PERCHE' NON browser.i18n / _locales
   browser.i18n risolve contro la lingua del BROWSER e non e' sovrascrivibile
   a runtime: getMessage() legge il locale del profilo Safari e basta. Qui la
   lingua e' una preferenza dell'utente, salvata in archivio e commutabile con
   un clic senza ricaricare niente. Sono due cose diverse, e la seconda non si
   puo' costruire sopra la prima. _locales resta usato per UNA cosa sola: nome
   e descrizione nel manifest, che li legge il sistema e non noi.

   STRUTTURA
   Le voci stanno in UNA tabella di coppie [it, en]. Non due dizionari
   affiancati che possono divergere: una coppia incompleta e' visibile a
   colpo d'occhio, e I18N.audit() la trova comunque.

   COSA NON SI TRADUCE
   Titoli di film, note dell'utente, nomi dei profili, metadati delle
   locandine. Sono contenuto, non interfaccia.
   ========================================================================== */

var I18N = (() => {
  const LANGS = ["it", "en"];
  const FALLBACK = "it";

  /* ---------------------------------------------------------------- voci --
     Chiave: [italiano, inglese].
     {n}, {title}, {name} sono segnaposto sostituiti da t(key, vars).
     Le voci con .one / .other si scelgono con tn(key, n).
     ------------------------------------------------------------------- */
  const PAIRS = {
    /* --- identita' e cornice --- */
    "app.name":                 ["FOSFORO", "FOSFORO"],
    "app.tagline":              ["Il tuo diario di visione", "Your watch diary"],
    "app.docTitle":             ["Fosforo — Il tuo diario di visione", "Fosforo — Your watch diary"],
    "app.optionsTitle":         ["Fosforo — Impostazioni", "Fosforo — Settings"],
    "app.footerLeft":           ["Il tuo diario di visione · consigli generati da Claude", "Your watch diary · recommendations generated by Claude"],
    /* Questa riga e' una promessa, e ora e' di nuovo vera senza asterischi: il
       trailer si apre in una scheda di YouTube, cioe' ci vai tu, e lo vedi.
       Con il player incorporato la dashboard contattava YouTube da sola, e
       allora la riga andava corretta; adesso non c'e' piu' niente da correggere. */
    "app.footerRight":          ["Omaggio stilistico · non affiliato a Netflix · i dati restano sul tuo dispositivo", "Stylistic homage · not affiliated with Netflix · your data stays on your device"],

    /* --- trailer --- */
    "trailer.watch":            ["Guarda Trailer", "Watch Trailer"],
    "trailer.aria":             ["Guarda il trailer di {title} su YouTube, in una nuova scheda", "Watch the trailer for {title} on YouTube, in a new tab"],

    /* --- barra di navigazione --- */
    "nav.sections":             ["Sezioni", "Sections"],
    "nav.recs":                 ["CONSIGLIATI", "RECOMMENDED"],
    "nav.library":              ["LIBRERIA", "LIBRARY"],
    "nav.history":              ["CRONOLOGIA", "HISTORY"],
    "nav.you":                  ["PROFILO", "PROFILE"],
    "nav.settings":             ["IMPOSTAZIONI", "SETTINGS"],
    "nav.search":               ["CERCA", "SEARCH"],
    "nav.searchAria":           ["Cerca nella libreria", "Search your library"],
    "nav.add":                  ["AGGIUNGI", "ADD"],
    "nav.addAria":              ["Aggiungi un titolo che hai già visto", "Add a title you have already watched"],
    "nav.langAria":             ["Lingua dell'interfaccia", "Interface language"],
    "nav.langTo":               ["Passa all'inglese", "Switch to Italian"],

    /* --- spia LIVE --- */
    "live.id":                  ["LIVE", "LIVE"],
    "live.idle":                ["IN ASCOLTO", "LISTENING"],
    "live.tracking":            ["TRACCIO", "TRACKING"],
    "live.recs":                ["CONSIGLI", "ADVISING"],
    "live.posters":             ["LOCANDINE", "POSTERS"],
    "live.offline":             ["OFFLINE", "OFFLINE"],
    "live.error":               ["ERRORE", "FAULT"],
    "live.noKey":               ["NO CHIAVE", "NO KEY"],

    /* --- letture di testata --- */
    "stat.titles":              ["TITOLI", "TITLES"],
    "stat.sources":             ["SORGENTI", "SOURCES"],
    "stat.lastSync":            ["ULTIMO SYNC", "LAST SYNC"],
    "stat.syncToday":           ["SYNC OGGI", "SYNC TODAY"],
    "stat.never":               ["MAI", "NEVER"],
    "stat.pending":             ["DA CONFERMARE", "TO CONFIRM"],

    /* --- distanze nel tempo (maiuscolo: sono readout) --- */
    "ago.today":                ["OGGI", "TODAY"],
    "ago.yesterday":            ["IERI", "YESTERDAY"],
    "ago.days":                 ["{n} GIORNI FA", "{n} DAYS AGO"],
    "ago.weeks.one":            ["1 SETTIMANA FA", "1 WEEK AGO"],
    "ago.weeks.other":          ["{n} SETTIMANE FA", "{n} WEEKS AGO"],
    "ago.months.one":           ["1 MESE FA", "1 MONTH AGO"],
    "ago.months.other":         ["{n} MESI FA", "{n} MONTHS AGO"],
    "ago.years.one":            ["1 ANNO FA", "1 YEAR AGO"],
    "ago.years.other":          ["{n} ANNI FA", "{n} YEARS AGO"],

    /* --- tipi, unita', vocabolario controllato --- */
    "type.film":                ["Film", "Movie"],
    "type.serie":               ["Serie", "Series"],
    "unit.min":                 ["{n} MIN", "{n} MIN"],
    "unit.seasons.one":         ["1 STAGIONE", "1 SEASON"],
    "unit.seasons.other":       ["{n} STAGIONI", "{n} SEASONS"],
    "unit.episodes.one":        ["1 PUNTATA", "1 EPISODE"],
    "unit.episodes.other":      ["{n} PUNTATE", "{n} EPISODES"],
    "unit.of100":               ["SU 100", "OF 100"],

    "rating.amato":             ["Amato", "Loved"],
    "rating.piaciuto":          ["Piaciuto", "Liked"],
    "rating.neutro":            ["Nella media", "Average"],
    "rating.no":                ["Non fa per me", "Not for me"],

    "genre.Azione":             ["Azione", "Action"],
    "genre.Avventura":          ["Avventura", "Adventure"],
    "genre.Animazione":         ["Animazione", "Animation"],
    "genre.Commedia":           ["Commedia", "Comedy"],
    "genre.Crime":              ["Crime", "Crime"],
    "genre.Documentario":       ["Documentario", "Documentary"],
    "genre.Dramma":             ["Dramma", "Drama"],
    "genre.Fantascienza":       ["Fantascienza", "Sci-Fi"],
    "genre.Fantasy":            ["Fantasy", "Fantasy"],
    "genre.Horror":             ["Horror", "Horror"],
    "genre.Mistero":            ["Mistero", "Mystery"],
    "genre.Romantico":          ["Romantico", "Romance"],
    "genre.Storico":            ["Storico", "Historical"],
    "genre.Thriller":           ["Thriller", "Thriller"],

    /* --- hero --- */
    "hero.firstRun.kicker":     ["PRIMO AVVIO", "FIRST RUN"],
    "hero.firstRun.title":      ["Dimmi tre film che hai amato", "Tell me three films you loved"],
    "hero.firstRun.why":        ["Bastano tre titoli con un voto perché Claude cominci a capire i tuoi gusti. Puoi aggiungerli a mano, oppure lasciare che Fosforo li registri da solo mentre guardi.", "Three rated titles are enough for Claude to start reading your taste. Add them by hand, or let Fosforo record them on its own while you watch."],
    "hero.firstRun.add":        ["＋ AGGIUNGI UN TITOLO", "＋ ADD A TITLE"],
    "hero.firstRun.how":        ["COME FUNZIONA LA REGISTRAZIONE", "HOW TRACKING WORKS"],
    "hero.top.kicker":          ["CONSIGLIO PRINCIPALE", "TOP RECOMMENDATION"],
    "hero.top.toList":          ["AGGIUNGI ALLA LISTA", "ADD TO MY LIST"],
    "hero.top.details":         ["DETTAGLI", "DETAILS"],
    "hero.top.dismiss":         ["NON MI INTERESSA", "NOT INTERESTED"],
    "hero.lib.kicker":          ["DALLA TUA LIBRERIA", "FROM YOUR LIBRARY"],
    "hero.lib.fallbackTitle":   ["La tua libreria", "Your library"],
    "hero.lib.why":             ["Premi «Aggiorna» e Claude userà quello che hai visto finora per proporti cosa guardare stasera.", "Press “Refresh” and Claude will use what you have watched so far to suggest what to watch tonight."],
    "hero.lib.generate":        ["GENERA CONSIGLI", "GENERATE RECOMMENDATIONS"],
    "hero.lib.fav":             ["PREFERITO", "FAVOURITE"],
    "hero.coverLabel":          ["COVER 2:3", "COVER 2:3"],

    /* --- binario affinita' --- */
    "rail.affinity":            ["AFFINITÀ", "AFFINITY"],
    "rail.type":                ["TIPO", "TYPE"],
    "rail.release":             ["USCITA", "RELEASE"],
    "rail.inList":              ["IN LISTA", "IN LIST"],
    "rail.similarSeen":         ["SIMILI VISTI", "SIMILAR SEEN"],
    "rail.yes":                 ["SÌ", "YES"],
    "rail.no":                  ["NO", "NO"],

    /* --- quarantena --- */
    "pending.head":             ["DA CONFERMARE", "TO CONFIRM"],
    "pending.discardAll":       ["SCARTA TUTTI", "DISCARD ALL"],
    "pending.note":             ["Fosforo ha registrato questi titoli mentre navigavi, ma non è sicuro che siano film o serie. Quello che confermi entra in libreria e viene usato per i consigli.", "Fosforo recorded these titles while you browsed, but it is not sure they are films or series. Whatever you confirm enters your library and feeds the recommendations."],
    "pending.isTitle":          ["È UN TITOLO", "IT IS A TITLE"],
    "pending.notTitle":         ["NO", "NO"],
    "pending.added":            ["«{title}» è in libreria.", "“{title}” is in your library."],

    /* --- motivi di quarantena (scritti da store.js) --- */
    "doubt.counter":            ["Comincia con un contatore di notifiche", "Starts with a notification counter"],
    "doubt.username":           ["Contiene un nome utente", "Contains a username"],
    "doubt.social":             ["Sembra il titolo di una pagina social", "Looks like a social page title"],
    "doubt.url":                ["Contiene un indirizzo web", "Contains a web address"],
    "doubt.servicePage":        ["Sembra una pagina di servizio", "Looks like a utility page"],
    "doubt.tooShort":           ["Titolo troppo corto", "Title too short"],
    "doubt.tooLong":            ["Titolo troppo lungo per essere un film", "Title too long to be a film"],
    "doubt.notDeclared":        ["La pagina non dichiara di essere un film o una serie", "The page does not declare itself a film or a series"],

    /* --- consigli --- */
    "recs.head":                ["CONSIGLIATI PER TE", "RECOMMENDED FOR YOU"],
    "recs.refresh":             ["AGGIORNA →", "REFRESH →"],
    "recs.cancel":              ["ANNULLA", "CANCEL"],
    "recs.waiting":             ["IN ATTESA", "WAITING"],
    "recs.emptyTitle":          ["Ancora nessun consiglio", "No recommendations yet"],
    "recs.emptyBody":           ["Premi Aggiorna e Claude userà la tua libreria per proporti cosa guardare stasera.", "Press Refresh and Claude will use your library to suggest what to watch tonight."],
    "recs.faultKey":            ["GUASTO · CHIAVE API", "FAULT · API KEY"],
    "recs.fault":               ["GUASTO", "FAULT"],
    "recs.faultTitle":          ["Claude non risponde", "Claude is not answering"],
    "recs.openSettings":        ["APRI IMPOSTAZIONI", "OPEN SETTINGS"],
    "recs.retry":               ["RIPROVA", "RETRY"],
    "recs.staleNote":           ["ULTIMI CONSIGLI VALIDI · {when}", "LAST VALID RECOMMENDATIONS · {when}"],
    "recs.staleSoon":           ["POCO FA", "JUST NOW"],
    "recs.affinity":            ["AFFINITÀ", "AFFINITY"],
    "recs.dismissAria":         ["Non propormi più {title}", "Stop recommending {title}"],
    "recs.detailsAria":         ["{title}, dettagli", "{title}, details"],
    "recs.phase1":              ["CLAUDE STA LEGGENDO LA TUA LIBRERIA…", "CLAUDE IS READING YOUR LIBRARY…"],
    "recs.phase2":              ["CONFRONTO CON I TUOI VOTI…", "WEIGHING YOUR RATINGS…"],
    "recs.phase3":              ["SCARTO CIÒ CHE HAI GIÀ VISTO…", "DROPPING WHAT YOU HAVE SEEN…"],
    "recs.phase4":              ["COMPONGO LE PROPOSTE…", "COMPOSING THE PROPOSALS…"],
    "recs.reading":             ["CLAUDE STA LEGGENDO {n} TITOLI…", "CLAUDE IS READING {n} TITLES…"],

    /* --- sezioni della libreria --- */
    "rows.resume":              ["CONTINUA A GUARDARE", "CONTINUE WATCHING"],
    "rows.myList":              ["LA MIA LISTA", "MY LIST"],
    "rows.unrated":             ["DA VOTARE", "TO RATE"],
    "rows.loved":               ["I TUOI PREFERITI", "YOUR FAVOURITES"],
    "rows.liked":               ["TI SONO PIACIUTI", "YOU LIKED THESE"],
    "rows.rest":                ["ANCHE VISTI", "ALSO WATCHED"],
    "card.toWatch":             ["DA VEDERE", "TO WATCH"],
    "card.toRate":              ["DA VOTARE", "TO RATE"],

    /* --- ricerca --- */
    "search.noneCode":          ["NESSUNA CORRISPONDENZA", "NO MATCH"],
    "search.noneTitle":         ["«{q}» non è nella tua libreria", "“{q}” is not in your library"],
    "search.noneBody":          ["Nessun titolo, consiglio o genere corrisponde. Puoi cancellare la ricerca, oppure aggiungerlo come titolo che hai visto.", "No title, recommendation or genre matches. You can clear the search, or add it as a title you have watched."],
    "search.clear":             ["CANCELLA RICERCA", "CLEAR SEARCH"],
    "search.addQuery":          ["＋ AGGIUNGI «{q}»", "＋ ADD “{q}”"],

    /* --- schede modali --- */
    "modal.close":              ["Chiudi", "Close"],
    "modal.fromClaude":         ["CONSIGLIATO DA CLAUDE", "RECOMMENDED BY CLAUDE"],
    "modal.myList":             ["LA MIA LISTA", "MY LIST"],
    "modal.yourLibrary":        ["LA TUA LIBRERIA", "YOUR LIBRARY"],
    "modal.addToList":          ["＋ AGGIUNGI ALLA LISTA", "＋ ADD TO MY LIST"],
    "modal.alreadySeen":        ["L'HO GIÀ VISTO…", "I HAVE SEEN IT…"],
    "modal.notInterested":      ["NON MI INTERESSA", "NOT INTERESTED"],
    "modal.markSeen":           ["✓ SEGNA COME VISTO", "✓ MARK AS WATCHED"],
    "modal.removeFromList":     ["RIMUOVI DALLA LISTA", "REMOVE FROM LIST"],
    "modal.editDetails":        ["MODIFICA DETTAGLI", "EDIT DETAILS"],
    "modal.delete":             ["ELIMINA", "DELETE"],
    "modal.affinityOf":         ["AFFINITÀ {n} SU 100", "AFFINITY {n} OF 100"],

    /* --- modulo --- */
    "form.tagNew":              ["NUOVO TITOLO", "NEW TITLE"],
    "form.tagEdit":             ["MODIFICA", "EDIT"],
    "form.tagFromWatch":        ["SEGNA COME VISTO", "MARK AS WATCHED"],
    "form.addTitle":            ["Aggiungi un titolo", "Add a title"],
    "form.title":               ["Titolo", "Title"],
    "form.titlePlaceholder":    ["Es. Il Padrino", "e.g. The Godfather"],
    "form.type":                ["Tipo", "Type"],
    "form.year":                ["Anno", "Year"],
    "form.genre":               ["Genere", "Genre"],
    "form.rating":              ["Il tuo voto", "Your rating"],
    "form.note":                ["Nota (facoltativa)", "Note (optional)"],
    "form.notePlaceholder":     ["Cosa ti è piaciuto o no…", "What you liked or didn't…"],
    "form.saveEdit":            ["SALVA MODIFICHE", "SAVE CHANGES"],
    "form.saveNew":             ["AGGIUNGI ALLA LIBRERIA", "ADD TO LIBRARY"],
    "form.cancel":              ["ANNULLA", "CANCEL"],

    /* --- avvisi --- */
    "toast.undo":               ["ANNULLA", "UNDO"],
    "toast.addedToList":        ["AGGIUNTO ALLA LISTA · {title}", "ADDED TO LIST · {title}"],
    "toast.rated":              ["«{title}» → {rating}", "“{title}” → {rating}"],
    "toast.dismissed":          ["«{title}» non te lo propongo più.", "“{title}” will not be suggested again."],
    "toast.needTitle":          ["Aggiungi almeno un titolo: Claude parte da lì.", "Add at least one title: that is where Claude starts."],
    "toast.profileSwitched":    ["Profilo attivo: {name}", "Active profile: {name}"],
    "toast.profileCreated":     ["Profilo «{name}» creato e attivo.", "Profile “{name}” created and active."],
    "toast.profileDeleted":     ["Profilo «{name}» eliminato.", "Profile “{name}” deleted."],

    /* --- errori mostrati all'utente --- */
    "err.generic":              ["Errore.", "Something went wrong."],
    "err.unknown":              ["Errore sconosciuto.", "Unknown error."],
    "err.timeout":              ["Claude non ha risposto entro {n} secondi. Riprova.", "Claude did not answer within {n} seconds. Try again."],
    "err.offline":              ["Richiesta bloccata: controlla la connessione, i permessi dell'estensione nel browser o un blocco contenuti.", "Request blocked: check your connection, the extension permissions in your browser, or a content blocker."],
    "err.badKey":               ["Chiave API non valida: controllala nelle impostazioni.", "Invalid API key: check it in settings."],
    "err.rate":                 ["Troppe richieste o credito esaurito: riprova più tardi.", "Too many requests or no credit left: try again later."],
    "err.rejected":             ["Richiesta rifiutata dal servizio.", "The service rejected the request."],
    "err.server":               ["Il servizio non risponde: riprova tra poco.", "The service is not responding: try again shortly."],
    "err.status":               ["Errore {n}.", "Error {n}."],
    "err.unreadable":           ["Non sono riuscito a leggere i consigli. Riprova.", "I could not read the recommendations. Try again."],
    "err.broken":               ["La risposta si \u00e8 interrotta a met\u00e0. Riprova.", "The response was cut off midway. Try again."],
    "err.busy":                 ["Sto già generando i consigli.", "I am already generating recommendations."],
    "mock.reason":              ["Demo: nessuna chiave API configurata.", "Demo: no API key configured."],
    "err.needLibrary":          ["Aggiungi qualche titolo prima di generare i consigli.", "Add a few titles before generating recommendations."],

    /* --- popup --- */
    "pop.settings":             ["Impostazioni", "Settings"],
    "pop.currentSite":          ["SITO CORRENTE", "CURRENT SITE"],
    "pop.panelOn":              ["PANNELLO ATTIVO", "PANEL ON"],
    "pop.panelOff":             ["PANNELLO SPENTO", "PANEL OFF"],
    "pop.enablePanel":          ["Pannello su questo sito", "Panel on this site"],
    "pop.disablePanel":         ["Togli il pannello qui", "Turn the panel off here"],
    "pop.reload":               ["Ricarica la pagina per vedere il cambiamento.", "Reload the page to see the change."],
    "pop.recommend":            ["↻ CONSIGLIAMI", "↻ RECOMMEND"],
    "pop.more":                 ["↻ ALTRI CONSIGLI", "↻ MORE"],
    "pop.generating":           ["GENERO…", "GENERATING…"],
    "pop.library":              ["LIBRERIA", "LIBRARY"],
    "pop.demo":                 ["Modalità demo: manca la chiave API.", "Demo mode: no API key set."],
    "pop.statTitles.one":       ["1 titolo in libreria", "1 title in library"],
    "pop.statTitles.other":     ["{n} titoli in libreria", "{n} titles in library"],
    "pop.statList":             ["{n} in lista", "{n} in list"],
    "pop.statUnrated":          ["{n} da votare", "{n} to rate"],

    /* --- pannello sui siti --- */
    "panel.tag":                ["FOSFORO", "FOSFORO"],
    "panel.title":              ["Cosa guardo stasera", "What to watch tonight"],
    "panel.hint":               ["Premi «Consigliami»: Claude sceglie sui titoli che hai già visto.", "Press “Recommend”: Claude picks from the titles you have already watched."],
    "panel.go":                 ["↻ Consigliami", "↻ Recommend"],
    "panel.more":               ["↻ Altri consigli", "↻ More"],
    "panel.generating":         ["Genero…", "Generating…"],
    "panel.openLibrary":        ["Libreria", "Library"],
    "panel.openLibraryTitle":   ["Apri la libreria", "Open your library"],
    "panel.add":                ["＋ Alla lista", "＋ To my list"],
    "panel.added":              ["✓ In lista", "✓ In list"],
    "panel.copy":               ["Copia titolo", "Copy title"],
    "panel.copied":             ["Copiato", "Copied"],
    "panel.skip":               ["Scarta", "Skip"],
    "panel.demo":               ["Modalità demo: aggiungi la chiave API nelle impostazioni.", "Demo mode: add your API key in settings."],
    "panel.close":              ["Chiudi", "Close"],

    /* --- impostazioni --- */
    "opts.title":               ["Impostazioni", "Settings"],
    "opts.lang":                ["Lingua", "Language"],
    "opts.langNote":            ["Vale per tutta l'interfaccia e per la lingua in cui Claude scrive i consigli. Cambia subito, senza ricaricare niente. Titoli, note e nomi dei profili restano come li hai scritti.", "Applies to the whole interface and to the language Claude writes recommendations in. It changes immediately, with no reload. Titles, notes and profile names stay exactly as you wrote them."],
    "opts.langIt":              ["Italiano", "Italian"],
    "opts.langEn":              ["Inglese", "English"],
    "opts.apiKey":              ["Chiave API", "API key"],
    "opts.apiKeyNote":          ["Serve una chiave da console.anthropic.com. Resta su questo Mac e non viene inviata da nessun'altra parte. Senza chiave l'estensione funziona in modalità demo.", "You need a key from console.anthropic.com. It stays on this Mac and is never sent anywhere else. Without a key the extension runs in demo mode."],
    "opts.posters":             ["Locandine", "Posters"],
    "opts.postersNote":         ["Facoltativa. Accetta una chiave <strong>TMDB</strong> o <strong>OMDb</strong>: riconosco da sola quale delle due è. Senza chiave le copertine arrivano da TVmaze e Wikipedia, che sono gratuite ma di qualità più bassa. Le copertine dei titoli che apri tu vengono comunque prese dal sito stesso, e restano le migliori.", "Optional. Accepts a <strong>TMDB</strong> or an <strong>OMDb</strong> key: I work out which one it is on my own. Without a key, covers come from TVmaze and Wikipedia, which are free but lower quality. Covers for titles you open yourself are still taken from the site itself, and remain the best ones."],
    "opts.posterPlaceholder":   ["chiave TMDB o OMDb", "TMDB or OMDb key"],
    "opts.keyNone":             ["Nessuna chiave: uso TVmaze e Wikipedia.", "No key: using TVmaze and Wikipedia."],
    "opts.keyTmdb":             ["Riconosciuta come chiave TMDB.", "Recognised as a TMDB key."],
    "opts.keyOmdb":             ["Riconosciuta come chiave OMDb.", "Recognised as an OMDb key."],
    "opts.keyUnknown":          ["Formato non riconosciuto: la tratto come TMDB.", "Format not recognised: treating it as TMDB."],
    "opts.bulk":                ["Aggiungi titoli in blocco", "Add titles in bulk"],
    "opts.bulkNote":            ["Un titolo per riga, per partire senza aspettare che il tracciamento faccia il suo lavoro. Puoi scrivere anche <span class=\"mono\">Titolo (2019)</span>.", "One title per line, to get going without waiting for tracking to do its work. You can also write <span class=\"mono\">Title (2019)</span>."],
    "opts.bulkAdd":             ["Aggiungi alla libreria", "Add to library"],
    "opts.bulkDone.one":        ["1 titolo aggiunto.", "1 title added."],
    "opts.bulkDone.other":      ["{n} titoli aggiunti.", "{n} titles added."],
    "opts.sites":               ["Siti", "Sites"],
    "opts.sitesNote":           ["Un dominio per riga. Il pannello compare solo sui siti elencati qui: puoi aggiungere quello che stai visitando con un clic dal popup nella barra.", "One domain per line. The panel only appears on the sites listed here: you can add the one you are visiting with a click from the toolbar popup."],
    "opts.showPanelOn":         ["Mostra il pannello su", "Show the panel on"],
    "opts.neverTrack":          ["Non tracciare mai", "Never track"],
    "opts.library":             ["Libreria", "Library"],
    "opts.libraryNote":         ["I tuoi titoli vivono solo su questo Mac e sono legati all'estensione: se la reinstalli, spariscono. Il file esportato contiene i titoli, i giudizi e i siti — <strong>non</strong> le chiavi API. All'importazione niente viene sovrascritto: i titoli nuovi si aggiungono, quelli che hai già restano come sono.", "Your titles live only on this Mac and are tied to the extension: reinstall it and they are gone. The exported file contains titles, ratings and sites — <strong>not</strong> your API keys. Nothing is overwritten on import: new titles are added, the ones you already have stay as they are."],
    "opts.libraryScope":        ["Esportazione, importazione e svuotamento lavorano sul profilo attivo: <strong>{name}</strong>.", "Export, import and erase all act on the active profile: <strong>{name}</strong>."],
    "opts.export":              ["Esporta un file", "Export a file"],
    "opts.import":              ["Importa da file", "Import from file"],
    "opts.openLibrary":         ["Apri la libreria", "Open your library"],
    "opts.clear":               ["Svuota tutto", "Erase everything"],
    "opts.clearArmed":          ["Sicuro? Ripremi per svuotare", "Sure? Press again to erase"],
    "opts.clearWarn":           ["Se non l'hai già fatto, esporta prima un file.", "If you have not already, export a file first."],
    "opts.cleared":             ["Libreria svuotata.", "Library erased."],
    "opts.restore":             ["Ripristina", "Restore"],
    "opts.libEmpty":            ["Nessun titolo in libreria.", "No titles in your library."],
    "opts.libInfo":             ["{total} titoli ({auto} registrati da soli, {unrated} ancora da votare) · {list} in lista da guardare.", "{total} titles ({auto} recorded automatically, {unrated} still to rate) · {list} on your watch list."],
    "opts.dismissed.one":       ["1 titolo scartato dai consigli: non verrà più proposto.", "1 title dropped from recommendations: it will not be suggested again."],
    "opts.dismissed.other":     ["{n} titoli scartati dai consigli: non verranno più proposti.", "{n} titles dropped from recommendations: they will not be suggested again."],
    "opts.dismissReset":        ["{n} titoli tornano proponibili. Aggiorna i consigli per rivederli.", "{n} titles can be suggested again. Refresh the recommendations to see them."],
    "opts.save":                ["Salva", "Save"],
    "opts.saved":               ["Salvato.", "Saved."],
    "opts.savedPosters":        ["Salvato. Riapri la libreria per aggiornare le locandine.", "Saved. Reopen your library to refresh the posters."],
    "opts.exported":            ["{n} titoli esportati in {file}", "{n} titles exported to {file}"],
    "opts.importBadJson":       ["Il file non è leggibile: non è un JSON valido.", "The file is unreadable: it is not valid JSON."],
    "opts.importNotBackup":     ["Questo non sembra un backup di Fosforo.", "This does not look like a Fosforo backup."],
    "opts.importDone":          ["Importato: {parts}.", "Imported: {parts}."],
    "opts.importNothing":       ["Nel file non c'era niente di nuovo.", "There was nothing new in the file."],
    "opts.importAdded":         ["{n} titoli aggiunti", "{n} titles added"],
    "opts.importFilled":        ["{n} completati", "{n} completed"],
    "opts.importSame":          ["{n} già presenti", "{n} already there"],
    "opts.importList":          ["{n} nella lista da guardare", "{n} on the watch list"],

    /* --- profili --- */
    "prof.head":                ["PROFILO", "PROFILE"],
    "prof.title":               ["Chi sta guardando", "Who's watching"],
    "prof.honest":              ["I profili tengono separate le librerie, non i dati: sono locali, senza password e senza cifratura. Chi apre Fosforo su questo Mac può passare da un profilo all'altro e vedere tutto.", "Profiles keep libraries apart, not data: they are local, with no password and no encryption. Anyone who opens Fosforo on this Mac can switch profiles and see everything."],
    "prof.active":              ["ATTIVO", "ACTIVE"],
    "prof.switch":              ["PASSA A QUESTO", "SWITCH TO THIS"],
    "prof.switchAria":          ["Passa al profilo {name}", "Switch to the {name} profile"],
    "prof.new":                 ["＋ NUOVO PROFILO", "＋ NEW PROFILE"],
    "prof.newTag":              ["NUOVO PROFILO", "NEW PROFILE"],
    "prof.editTag":             ["MODIFICA PROFILO", "EDIT PROFILE"],
    "prof.name":                ["Nome", "Name"],
    "prof.namePlaceholder":     ["Es. Marianna", "e.g. Alex"],
    "prof.accent":              ["Colore", "Accent"],
    "prof.create":              ["CREA PROFILO", "CREATE PROFILE"],
    "prof.rename":              ["SALVA", "SAVE"],
    "prof.edit":                ["MODIFICA", "EDIT"],
    "prof.delete":              ["ELIMINA PROFILO", "DELETE PROFILE"],
    "prof.deleteTag":           ["ELIMINA PROFILO", "DELETE PROFILE"],
    "prof.deleteWarn":          ["Elimini «{name}» e con lui {titles} titoli in libreria, {list} in lista e {pending} da confermare. Non si può annullare.", "You are deleting “{name}” and with it {titles} titles in the library, {list} on the list and {pending} awaiting confirmation. This cannot be undone."],
    "prof.deleteConfirm":       ["Scrivi «{name}» per confermare", "Type “{name}” to confirm"],
    "prof.deleteLast":          ["Questo è l'unico profilo: non si può eliminare. Crea prima un altro profilo.", "This is the only profile: it cannot be deleted. Create another profile first."],
    "prof.statTitles":          ["TITOLI", "TITLES"],
    "prof.statRated":           ["VOTATI", "RATED"],
    "prof.statList":            ["IN LISTA", "ON LIST"],
    "prof.statLoved":           ["AMATI", "LOVED"],
    "prof.statSince":           ["DAL", "SINCE"],
    "prof.statNever":           ["—", "—"],
    "prof.defaultName":         ["Principale", "Main"],
    "prof.nameTaken":           ["C'è già un profilo con questo nome.", "There is already a profile with that name."]
  };

  /* --------------------------------------------------------------- setup -- */

  const DICT = { it: Object.create(null), en: Object.create(null) };
  Object.keys(PAIRS).forEach((k) => {
    DICT.it[k] = PAIRS[k][0];
    DICT.en[k] = PAIRS[k][1];
  });

  let current = FALLBACK;
  const warned = Object.create(null);

  const warnOnce = (id, msg) => {
    if (warned[id]) return;
    warned[id] = true;
    try { console.warn("[Fosforo i18n] " + msg); } catch (e) { /* niente */ }
  };

  // "it", "it-IT", "IT" → "it". Qualunque altra cosa → "en".
  const pick = (tag) => (/^it/i.test(String(tag || "")) ? "it" : "en");

  const fill = (str, vars) => {
    if (!vars) return str;
    return String(str).replace(/\{(\w+)\}/g, (whole, name) =>
      Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole
    );
  };

  /* La voce esiste in almeno una lingua? Serve ad applyI18n: su una chiave
     sconosciuta il markup scritto a mano resta dov'è invece di essere
     sostituito da un nodo vuoto o dal nome della chiave. */
  const has = (key) => Object.prototype.hasOwnProperty.call(DICT[FALLBACK], key);

  function t(key, vars) {
    const k = String(key || "");
    const inLang = DICT[current] && DICT[current][k];
    if (inLang != null && inLang !== "") return fill(inLang, vars);

    const inFallback = DICT[FALLBACK][k];
    if (inFallback != null && inFallback !== "") {
      warnOnce("miss:" + current + ":" + k, 'voce "' + k + '" mancante in "' + current + '": uso l\'italiano.');
      return fill(inFallback, vars);
    }

    warnOnce("unknown:" + k, 'voce "' + k + '" sconosciuta.');
    return k;
  }

  // Plurale: le due lingue condividono la regola 1 / altro.
  const tn = (key, n, vars) =>
    t(key + (Number(n) === 1 ? ".one" : ".other"), Object.assign({ n: n }, vars || {}));

  /* --------------------------------------------------------------- markup --
     data-i18n="key"                              → testo del nodo
     data-i18n-html="key"                         → innerHTML (solo voci nostre)
     data-i18n-attr="placeholder:key,title:key"   → attributi
     Un solo passaggio traduce un sottoalbero qualunque: le righe costruite a
     runtime si traducono esattamente come il markup statico.
     ------------------------------------------------------------------- */
  function applyI18n(root) {
    const scope = root || (typeof document !== "undefined" ? document : null);
    if (!scope || !scope.querySelectorAll) return;

    const all = (sel) => {
      const list = Array.prototype.slice.call(scope.querySelectorAll(sel));
      if (scope.matches && scope.matches(sel)) list.unshift(scope);
      return list;
    };

    all("[data-i18n]").forEach((el) => {
      const k = el.getAttribute("data-i18n");
      if (has(k)) el.textContent = t(k, dataVars(el));
    });

    all("[data-i18n-html]").forEach((el) => {
      const k = el.getAttribute("data-i18n-html");
      if (has(k)) el.innerHTML = t(k, dataVars(el));
    });

    all("[data-i18n-attr]").forEach((el) => {
      String(el.getAttribute("data-i18n-attr") || "")
        .split(",")
        .forEach((pair) => {
          const bits = pair.split(":");
          const attr = String(bits[0] || "").trim();
          const k = String(bits[1] || "").trim();
          if (attr && has(k)) el.setAttribute(attr, t(k, dataVars(el)));
        });
    });
  }

  /* I segnaposto di una voce statica si riempiono da data-i18n-var-*, così
     una frase con un numero dentro resta una frase sola nel dizionario. */
  function dataVars(el) {
    if (!el.dataset) return null;
    let vars = null;
    Object.keys(el.dataset).forEach((k) => {
      if (k.indexOf("i18nVar") !== 0 || k.length <= 7) return;
      const name = k.charAt(7).toLowerCase() + k.slice(8);
      (vars || (vars = {}))[name] = el.dataset[k];
    });
    return vars;
  }

  function setLang(lang) {
    const next = LANGS.indexOf(lang) >= 0 ? lang : pick(lang);
    current = next;
    if (typeof document !== "undefined" && document.documentElement) {
      document.documentElement.lang = next;
    }
    return next;
  }

  const getLang = () => current;

  // Controllo di completezza: elenca le voci senza traduzione inglese.
  const audit = () =>
    Object.keys(PAIRS).filter((k) => PAIRS[k][1] == null || PAIRS[k][1] === "");

  return { LANGS, FALLBACK, DICT, t, tn, has, pick, fill, applyI18n, setLang, getLang, audit };
})();

if (typeof module !== "undefined" && module.exports) module.exports = I18N;
